// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.7.1
// source: proto_files/protocol.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录
//cmd:1003
type C_USER_LOGIN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegisterPlatform string `protobuf:"bytes,1,opt,name=register_platform,json=registerPlatform,proto3" json:"register_platform,omitempty"` //平台
	PlatformValue    string `protobuf:"bytes,2,opt,name=platform_value,json=platformValue,proto3" json:"platform_value,omitempty"`          //平台值
	UserId           uint32 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                              //玩家id
}

func (x *C_USER_LOGIN) Reset() {
	*x = C_USER_LOGIN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_USER_LOGIN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_USER_LOGIN) ProtoMessage() {}

func (x *C_USER_LOGIN) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_USER_LOGIN.ProtoReflect.Descriptor instead.
func (*C_USER_LOGIN) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *C_USER_LOGIN) GetRegisterPlatform() string {
	if x != nil {
		return x.RegisterPlatform
	}
	return ""
}

func (x *C_USER_LOGIN) GetPlatformValue() string {
	if x != nil {
		return x.PlatformValue
	}
	return ""
}

func (x *C_USER_LOGIN) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 登录返回
//cmd:10003
type S_USER_LOGIN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc         bool           `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`                           //是否成功;
	ErrMess        string         `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"`                         //错误信息;
	SyncTime       uint32         `protobuf:"varint,3,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`                     //最近一次同步数据时间(32位整型unix时间戳)
	LastLoginTime  uint32         `protobuf:"varint,4,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`    // 当前登录的时间(服务器当前时间)
	LastLogoffTime uint32         `protobuf:"varint,5,opt,name=last_logoff_time,json=lastLogoffTime,proto3" json:"last_logoff_time,omitempty"` // 最后一次退出时间
	PlayerPt       *PlayerPt      `protobuf:"bytes,6,opt,name=player_pt,json=playerPt,proto3" json:"player_pt,omitempty"`                      //玩家记录信息
	SeasonPt       *SeasonPt      `protobuf:"bytes,7,opt,name=season_pt,json=seasonPt,proto3" json:"season_pt,omitempty"`                      //当前赛季信息
	WorldBossPt    *WorldBossPt   `protobuf:"bytes,8,opt,name=world_boss_pt,json=worldBossPt,proto3" json:"world_boss_pt,omitempty"`           //当前worldboss
	Cters          []*CharacterPt `protobuf:"bytes,9,rep,name=cters,proto3" json:"cters,omitempty"`                                            //玩家角色
	GradeFrames    []uint32       `protobuf:"varint,10,rep,packed,name=grade_frames,json=gradeFrames,proto3" json:"grade_frames,omitempty"`    //玩家grade相框
	Souls          []uint32       `protobuf:"varint,11,rep,packed,name=souls,proto3" json:"souls,omitempty"`                                   //玩家soul头像
}

func (x *S_USER_LOGIN) Reset() {
	*x = S_USER_LOGIN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_USER_LOGIN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_USER_LOGIN) ProtoMessage() {}

func (x *S_USER_LOGIN) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_USER_LOGIN.ProtoReflect.Descriptor instead.
func (*S_USER_LOGIN) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *S_USER_LOGIN) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_USER_LOGIN) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

func (x *S_USER_LOGIN) GetSyncTime() uint32 {
	if x != nil {
		return x.SyncTime
	}
	return 0
}

func (x *S_USER_LOGIN) GetLastLoginTime() uint32 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

func (x *S_USER_LOGIN) GetLastLogoffTime() uint32 {
	if x != nil {
		return x.LastLogoffTime
	}
	return 0
}

func (x *S_USER_LOGIN) GetPlayerPt() *PlayerPt {
	if x != nil {
		return x.PlayerPt
	}
	return nil
}

func (x *S_USER_LOGIN) GetSeasonPt() *SeasonPt {
	if x != nil {
		return x.SeasonPt
	}
	return nil
}

func (x *S_USER_LOGIN) GetWorldBossPt() *WorldBossPt {
	if x != nil {
		return x.WorldBossPt
	}
	return nil
}

func (x *S_USER_LOGIN) GetCters() []*CharacterPt {
	if x != nil {
		return x.Cters
	}
	return nil
}

func (x *S_USER_LOGIN) GetGradeFrames() []uint32 {
	if x != nil {
		return x.GradeFrames
	}
	return nil
}

func (x *S_USER_LOGIN) GetSouls() []uint32 {
	if x != nil {
		return x.Souls
	}
	return nil
}

//心跳包请求，返回同一个，请求需要带参数
//cmd:10002
type HEART_BEAT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SysTime uint64 `protobuf:"varint,1,opt,name=sys_time,json=sysTime,proto3" json:"sys_time,omitempty"` //服务器当前时间
}

func (x *HEART_BEAT) Reset() {
	*x = HEART_BEAT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HEART_BEAT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HEART_BEAT) ProtoMessage() {}

func (x *HEART_BEAT) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HEART_BEAT.ProtoReflect.Descriptor instead.
func (*HEART_BEAT) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *HEART_BEAT) GetSysTime() uint64 {
	if x != nil {
		return x.SysTime
	}
	return 0
}

//同步数据请求
//cmd:1004
type C_SYNC_DATA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerPt *PlayerPt `protobuf:"bytes,1,opt,name=player_pt,json=playerPt,proto3" json:"player_pt,omitempty"` //玩家记录
}

func (x *C_SYNC_DATA) Reset() {
	*x = C_SYNC_DATA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_SYNC_DATA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_SYNC_DATA) ProtoMessage() {}

func (x *C_SYNC_DATA) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_SYNC_DATA.ProtoReflect.Descriptor instead.
func (*C_SYNC_DATA) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *C_SYNC_DATA) GetPlayerPt() *PlayerPt {
	if x != nil {
		return x.PlayerPt
	}
	return nil
}

//同步数据返回
//cmd:10004
type S_SYNC_DATA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc   bool   `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`       //是否成功;
	ErrMess  string `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"`     //错误信息;
	SyncTime uint32 `protobuf:"varint,3,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"` //同步数据时间(32位整型unix时间戳)
}

func (x *S_SYNC_DATA) Reset() {
	*x = S_SYNC_DATA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_SYNC_DATA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_SYNC_DATA) ProtoMessage() {}

func (x *S_SYNC_DATA) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_SYNC_DATA.ProtoReflect.Descriptor instead.
func (*S_SYNC_DATA) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *S_SYNC_DATA) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_SYNC_DATA) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

func (x *S_SYNC_DATA) GetSyncTime() uint32 {
	if x != nil {
		return x.SyncTime
	}
	return 0
}

//修改昵称请求
//cmd:1005
type C_MODIFY_NICK_NAME struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string `protobuf:"bytes,1,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"` //昵称
}

func (x *C_MODIFY_NICK_NAME) Reset() {
	*x = C_MODIFY_NICK_NAME{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_MODIFY_NICK_NAME) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_MODIFY_NICK_NAME) ProtoMessage() {}

func (x *C_MODIFY_NICK_NAME) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_MODIFY_NICK_NAME.ProtoReflect.Descriptor instead.
func (*C_MODIFY_NICK_NAME) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *C_MODIFY_NICK_NAME) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

//修改昵称返回
//cmd:10005
type S_MODIFY_NICK_NAME struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc  bool   `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`   //是否成功;
	ErrMess string `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"` //错误信息;
}

func (x *S_MODIFY_NICK_NAME) Reset() {
	*x = S_MODIFY_NICK_NAME{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_MODIFY_NICK_NAME) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_MODIFY_NICK_NAME) ProtoMessage() {}

func (x *S_MODIFY_NICK_NAME) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_MODIFY_NICK_NAME.ProtoReflect.Descriptor instead.
func (*S_MODIFY_NICK_NAME) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *S_MODIFY_NICK_NAME) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_MODIFY_NICK_NAME) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

//请求排行榜
//cmd:1012
type C_SHOW_RANK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C_SHOW_RANK) Reset() {
	*x = C_SHOW_RANK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_SHOW_RANK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_SHOW_RANK) ProtoMessage() {}

func (x *C_SHOW_RANK) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_SHOW_RANK.ProtoReflect.Descriptor instead.
func (*C_SHOW_RANK) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{7}
}

//请求排行榜返回
//cmd:10081
type S_SHOW_RANK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SelfRank *RankInfoPt   `protobuf:"bytes,1,opt,name=self_rank,json=selfRank,proto3" json:"self_rank,omitempty"` //自己的排行榜信息，如果在排行榜里面就有数据，不在就没有
	Ranks    []*RankInfoPt `protobuf:"bytes,2,rep,name=ranks,proto3" json:"ranks,omitempty"`                       //排行榜信息
}

func (x *S_SHOW_RANK) Reset() {
	*x = S_SHOW_RANK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_SHOW_RANK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_SHOW_RANK) ProtoMessage() {}

func (x *S_SHOW_RANK) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_SHOW_RANK.ProtoReflect.Descriptor instead.
func (*S_SHOW_RANK) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *S_SHOW_RANK) GetSelfRank() *RankInfoPt {
	if x != nil {
		return x.SelfRank
	}
	return nil
}

func (x *S_SHOW_RANK) GetRanks() []*RankInfoPt {
	if x != nil {
		return x.Ranks
	}
	return nil
}

//请求修改grade相框和soul头像
//cmd:1013
type C_MODIFY_GRADE_FRAME_AND_SOUL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Soul       uint32 `protobuf:"varint,1,opt,name=soul,proto3" json:"soul,omitempty"`                               //灵魂头像
	GradeFrame uint32 `protobuf:"varint,2,opt,name=grade_frame,json=gradeFrame,proto3" json:"grade_frame,omitempty"` //grade相框
}

func (x *C_MODIFY_GRADE_FRAME_AND_SOUL) Reset() {
	*x = C_MODIFY_GRADE_FRAME_AND_SOUL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_MODIFY_GRADE_FRAME_AND_SOUL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_MODIFY_GRADE_FRAME_AND_SOUL) ProtoMessage() {}

func (x *C_MODIFY_GRADE_FRAME_AND_SOUL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_MODIFY_GRADE_FRAME_AND_SOUL.ProtoReflect.Descriptor instead.
func (*C_MODIFY_GRADE_FRAME_AND_SOUL) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *C_MODIFY_GRADE_FRAME_AND_SOUL) GetSoul() uint32 {
	if x != nil {
		return x.Soul
	}
	return 0
}

func (x *C_MODIFY_GRADE_FRAME_AND_SOUL) GetGradeFrame() uint32 {
	if x != nil {
		return x.GradeFrame
	}
	return 0
}

//请求修改grade相框和soul头像返回
//cmd:1013
type S_MODIFY_GRADE_FRAME_AND_SOUL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc  bool   `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`   //是否成功;
	ErrMess string `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"` //错误信息;
}

func (x *S_MODIFY_GRADE_FRAME_AND_SOUL) Reset() {
	*x = S_MODIFY_GRADE_FRAME_AND_SOUL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_MODIFY_GRADE_FRAME_AND_SOUL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_MODIFY_GRADE_FRAME_AND_SOUL) ProtoMessage() {}

func (x *S_MODIFY_GRADE_FRAME_AND_SOUL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_MODIFY_GRADE_FRAME_AND_SOUL.ProtoReflect.Descriptor instead.
func (*S_MODIFY_GRADE_FRAME_AND_SOUL) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *S_MODIFY_GRADE_FRAME_AND_SOUL) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_MODIFY_GRADE_FRAME_AND_SOUL) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

//请求上赛季排行榜
//cmd:1015
type C_GET_LAST_SEASON_RANK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C_GET_LAST_SEASON_RANK) Reset() {
	*x = C_GET_LAST_SEASON_RANK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_GET_LAST_SEASON_RANK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_GET_LAST_SEASON_RANK) ProtoMessage() {}

func (x *C_GET_LAST_SEASON_RANK) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_GET_LAST_SEASON_RANK.ProtoReflect.Descriptor instead.
func (*C_GET_LAST_SEASON_RANK) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{11}
}

//请求上赛季排行榜返回
//cmd:10083
type S_GET_LAST_SEASON_RANK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ranks []*RankInfoPt `protobuf:"bytes,1,rep,name=ranks,proto3" json:"ranks,omitempty"` //排行榜信息
}

func (x *S_GET_LAST_SEASON_RANK) Reset() {
	*x = S_GET_LAST_SEASON_RANK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_protocol_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_GET_LAST_SEASON_RANK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_GET_LAST_SEASON_RANK) ProtoMessage() {}

func (x *S_GET_LAST_SEASON_RANK) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_protocol_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_GET_LAST_SEASON_RANK.ProtoReflect.Descriptor instead.
func (*S_GET_LAST_SEASON_RANK) Descriptor() ([]byte, []int) {
	return file_proto_files_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *S_GET_LAST_SEASON_RANK) GetRanks() []*RankInfoPt {
	if x != nil {
		return x.Ranks
	}
	return nil
}

var File_proto_files_protocol_proto protoreflect.FileDescriptor

var file_proto_files_protocol_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x0c,
	0x43, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x12, 0x2b, 0x0a, 0x11,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xac, 0x03, 0x0a, 0x0c, 0x53, 0x5f,
	0x55, 0x53, 0x45, 0x52, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73,
	0x5f, 0x73, 0x75, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53,
	0x75, 0x63, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x6f,
	0x66, 0x66, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6c,
	0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x6f, 0x66, 0x66, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2d, 0x0a,
	0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x70, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x50, 0x74, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x74, 0x12, 0x2d, 0x0a, 0x09,
	0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x5f, 0x70, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x50,
	0x74, 0x52, 0x08, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x50, 0x74, 0x12, 0x37, 0x0a, 0x0d, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x5f, 0x62, 0x6f, 0x73, 0x73, 0x5f, 0x70, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x42, 0x6f, 0x73, 0x73, 0x50, 0x74, 0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x42, 0x6f,
	0x73, 0x73, 0x50, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x63, 0x74, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x50, 0x74, 0x52, 0x05, 0x63, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x67, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x18,
	0x0a, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x67, 0x72, 0x61, 0x64, 0x65, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6f, 0x75, 0x6c, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x05, 0x73, 0x6f, 0x75, 0x6c, 0x73, 0x22, 0x27, 0x0a, 0x0a, 0x48, 0x45, 0x41, 0x52,
	0x54, 0x5f, 0x42, 0x45, 0x41, 0x54, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x79, 0x73, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x79, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x3c, 0x0a, 0x0b, 0x43, 0x5f, 0x53, 0x59, 0x4e, 0x43, 0x5f, 0x44, 0x41, 0x54, 0x41,
	0x12, 0x2d, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x70, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x50, 0x74, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x74, 0x22,
	0x5e, 0x0a, 0x0b, 0x53, 0x5f, 0x53, 0x59, 0x4e, 0x43, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x12, 0x17,
	0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x31, 0x0a, 0x12, 0x43, 0x5f, 0x4d, 0x4f, 0x44, 0x49, 0x46, 0x59, 0x5f, 0x4e, 0x49, 0x43, 0x4b,
	0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x48, 0x0a, 0x12, 0x53, 0x5f, 0x4d, 0x4f, 0x44, 0x49, 0x46, 0x59, 0x5f, 0x4e,
	0x49, 0x43, 0x4b, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73,
	0x75, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x75, 0x63,
	0x63, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x22, 0x0d, 0x0a, 0x0b,
	0x43, 0x5f, 0x53, 0x48, 0x4f, 0x57, 0x5f, 0x52, 0x41, 0x4e, 0x4b, 0x22, 0x68, 0x0a, 0x0b, 0x53,
	0x5f, 0x53, 0x48, 0x4f, 0x57, 0x5f, 0x52, 0x41, 0x4e, 0x4b, 0x12, 0x2f, 0x0a, 0x09, 0x73, 0x65,
	0x6c, 0x66, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x50,
	0x74, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x28, 0x0a, 0x05, 0x72,
	0x61, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x74, 0x52, 0x05,
	0x72, 0x61, 0x6e, 0x6b, 0x73, 0x22, 0x54, 0x0a, 0x1d, 0x43, 0x5f, 0x4d, 0x4f, 0x44, 0x49, 0x46,
	0x59, 0x5f, 0x47, 0x52, 0x41, 0x44, 0x45, 0x5f, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x41, 0x4e,
	0x44, 0x5f, 0x53, 0x4f, 0x55, 0x4c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x75, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6f, 0x75, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x67, 0x72, 0x61, 0x64, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x22, 0x53, 0x0a, 0x1d, 0x53,
	0x5f, 0x4d, 0x4f, 0x44, 0x49, 0x46, 0x59, 0x5f, 0x47, 0x52, 0x41, 0x44, 0x45, 0x5f, 0x46, 0x52,
	0x41, 0x4d, 0x45, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x53, 0x4f, 0x55, 0x4c, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x53, 0x75, 0x63, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x22, 0x18, 0x0a, 0x16, 0x43, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x4c, 0x41, 0x53, 0x54, 0x5f, 0x53,
	0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x52, 0x41, 0x4e, 0x4b, 0x22, 0x42, 0x0a, 0x16, 0x53, 0x5f,
	0x47, 0x45, 0x54, 0x5f, 0x4c, 0x41, 0x53, 0x54, 0x5f, 0x53, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f,
	0x52, 0x41, 0x4e, 0x4b, 0x12, 0x28, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x61, 0x6e,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x74, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x6b, 0x73, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_files_protocol_proto_rawDescOnce sync.Once
	file_proto_files_protocol_proto_rawDescData = file_proto_files_protocol_proto_rawDesc
)

func file_proto_files_protocol_proto_rawDescGZIP() []byte {
	file_proto_files_protocol_proto_rawDescOnce.Do(func() {
		file_proto_files_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_protocol_proto_rawDescData)
	})
	return file_proto_files_protocol_proto_rawDescData
}

var file_proto_files_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_files_protocol_proto_goTypes = []interface{}{
	(*C_USER_LOGIN)(nil),                  // 0: protos.C_USER_LOGIN
	(*S_USER_LOGIN)(nil),                  // 1: protos.S_USER_LOGIN
	(*HEART_BEAT)(nil),                    // 2: protos.HEART_BEAT
	(*C_SYNC_DATA)(nil),                   // 3: protos.C_SYNC_DATA
	(*S_SYNC_DATA)(nil),                   // 4: protos.S_SYNC_DATA
	(*C_MODIFY_NICK_NAME)(nil),            // 5: protos.C_MODIFY_NICK_NAME
	(*S_MODIFY_NICK_NAME)(nil),            // 6: protos.S_MODIFY_NICK_NAME
	(*C_SHOW_RANK)(nil),                   // 7: protos.C_SHOW_RANK
	(*S_SHOW_RANK)(nil),                   // 8: protos.S_SHOW_RANK
	(*C_MODIFY_GRADE_FRAME_AND_SOUL)(nil), // 9: protos.C_MODIFY_GRADE_FRAME_AND_SOUL
	(*S_MODIFY_GRADE_FRAME_AND_SOUL)(nil), // 10: protos.S_MODIFY_GRADE_FRAME_AND_SOUL
	(*C_GET_LAST_SEASON_RANK)(nil),        // 11: protos.C_GET_LAST_SEASON_RANK
	(*S_GET_LAST_SEASON_RANK)(nil),        // 12: protos.S_GET_LAST_SEASON_RANK
	(*PlayerPt)(nil),                      // 13: protos.PlayerPt
	(*SeasonPt)(nil),                      // 14: protos.SeasonPt
	(*WorldBossPt)(nil),                   // 15: protos.WorldBossPt
	(*CharacterPt)(nil),                   // 16: protos.CharacterPt
	(*RankInfoPt)(nil),                    // 17: protos.RankInfoPt
}
var file_proto_files_protocol_proto_depIdxs = []int32{
	13, // 0: protos.S_USER_LOGIN.player_pt:type_name -> protos.PlayerPt
	14, // 1: protos.S_USER_LOGIN.season_pt:type_name -> protos.SeasonPt
	15, // 2: protos.S_USER_LOGIN.world_boss_pt:type_name -> protos.WorldBossPt
	16, // 3: protos.S_USER_LOGIN.cters:type_name -> protos.CharacterPt
	13, // 4: protos.C_SYNC_DATA.player_pt:type_name -> protos.PlayerPt
	17, // 5: protos.S_SHOW_RANK.self_rank:type_name -> protos.RankInfoPt
	17, // 6: protos.S_SHOW_RANK.ranks:type_name -> protos.RankInfoPt
	17, // 7: protos.S_GET_LAST_SEASON_RANK.ranks:type_name -> protos.RankInfoPt
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_files_protocol_proto_init() }
func file_proto_files_protocol_proto_init() {
	if File_proto_files_protocol_proto != nil {
		return
	}
	file_proto_files_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_files_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_USER_LOGIN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_USER_LOGIN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HEART_BEAT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_SYNC_DATA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_SYNC_DATA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_protocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_MODIFY_NICK_NAME); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_protocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_MODIFY_NICK_NAME); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_protocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_SHOW_RANK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_protocol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_SHOW_RANK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_protocol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_MODIFY_GRADE_FRAME_AND_SOUL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_protocol_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_MODIFY_GRADE_FRAME_AND_SOUL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_protocol_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_GET_LAST_SEASON_RANK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_protocol_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_GET_LAST_SEASON_RANK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_files_protocol_proto_goTypes,
		DependencyIndexes: file_proto_files_protocol_proto_depIdxs,
		MessageInfos:      file_proto_files_protocol_proto_msgTypes,
	}.Build()
	File_proto_files_protocol_proto = out.File
	file_proto_files_protocol_proto_rawDesc = nil
	file_proto_files_protocol_proto_goTypes = nil
	file_proto_files_protocol_proto_depIdxs = nil
}
