// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.7.1
// source: proto_files/room.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//创建房间请求
//cmd:1006
type C_CREATE_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType uint32         `protobuf:"varint,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"` //房间类型
	Setting  *RoomSettingPt `protobuf:"bytes,2,opt,name=setting,proto3" json:"setting,omitempty"`                    //房间设置,只有自定义房间的时候需要传，其他房间类型不要传
}

func (x *C_CREATE_ROOM) Reset() {
	*x = C_CREATE_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_CREATE_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_CREATE_ROOM) ProtoMessage() {}

func (x *C_CREATE_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_CREATE_ROOM.ProtoReflect.Descriptor instead.
func (*C_CREATE_ROOM) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{0}
}

func (x *C_CREATE_ROOM) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *C_CREATE_ROOM) GetSetting() *RoomSettingPt {
	if x != nil {
		return x.Setting
	}
	return nil
}

//加入房间
//cmd:1007
type C_JOIN_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   uint32 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`       //房间id
	RoomType uint32 `protobuf:"varint,2,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"` //房间类型
}

func (x *C_JOIN_ROOM) Reset() {
	*x = C_JOIN_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_JOIN_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_JOIN_ROOM) ProtoMessage() {}

func (x *C_JOIN_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_JOIN_ROOM.ProtoReflect.Descriptor instead.
func (*C_JOIN_ROOM) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{1}
}

func (x *C_JOIN_ROOM) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *C_JOIN_ROOM) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

//快速开始
//cmd:1008
type C_SEARCH_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType uint32 `protobuf:"varint,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"` //房间类型
}

func (x *C_SEARCH_ROOM) Reset() {
	*x = C_SEARCH_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_SEARCH_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_SEARCH_ROOM) ProtoMessage() {}

func (x *C_SEARCH_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_SEARCH_ROOM.ProtoReflect.Descriptor instead.
func (*C_SEARCH_ROOM) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{2}
}

func (x *C_SEARCH_ROOM) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

//房间协议返回，对应返回的有：1006，1007，1008
//cmd:10006
type S_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc  bool    `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`    //是否成功;
	ErrMess string  `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"`  //错误信息;
	ErrCode uint32  `protobuf:"varint,3,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"` //错误码;101:玩家已经在房间内   102:房间不存在   103:房间已开始 104:房间人满了
	Room    *RoomPt `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`                       //房间数据
}

func (x *S_ROOM) Reset() {
	*x = S_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_ROOM) ProtoMessage() {}

func (x *S_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_ROOM.ProtoReflect.Descriptor instead.
func (*S_ROOM) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{3}
}

func (x *S_ROOM) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_ROOM) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

func (x *S_ROOM) GetErrCode() uint32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *S_ROOM) GetRoom() *RoomPt {
	if x != nil {
		return x.Room
	}
	return nil
}

//房间设置请求
//cmd:20011
type C_ROOM_SETTING struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetType uint32 `protobuf:"varint,1,opt,name=set_type,json=setType,proto3" json:"set_type,omitempty"` //设定的类型 1:赛季开关 2:turn限制时间 3:AI 等级
	Value   int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`                    //对应的值
}

func (x *C_ROOM_SETTING) Reset() {
	*x = C_ROOM_SETTING{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_ROOM_SETTING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_ROOM_SETTING) ProtoMessage() {}

func (x *C_ROOM_SETTING) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_ROOM_SETTING.ProtoReflect.Descriptor instead.
func (*C_ROOM_SETTING) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{4}
}

func (x *C_ROOM_SETTING) GetSetType() uint32 {
	if x != nil {
		return x.SetType
	}
	return 0
}

func (x *C_ROOM_SETTING) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

//房间设置返回
//cmd:10011
type S_ROOM_SETTING struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc  bool   `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`   //是否成功;
	ErrMess string `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"` //错误信息;
}

func (x *S_ROOM_SETTING) Reset() {
	*x = S_ROOM_SETTING{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_ROOM_SETTING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_ROOM_SETTING) ProtoMessage() {}

func (x *S_ROOM_SETTING) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_ROOM_SETTING.ProtoReflect.Descriptor instead.
func (*S_ROOM_SETTING) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{5}
}

func (x *S_ROOM_SETTING) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_ROOM_SETTING) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

//离开房间
//cmd:20004
type C_LEAVE_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C_LEAVE_ROOM) Reset() {
	*x = C_LEAVE_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_LEAVE_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_LEAVE_ROOM) ProtoMessage() {}

func (x *C_LEAVE_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_LEAVE_ROOM.ProtoReflect.Descriptor instead.
func (*C_LEAVE_ROOM) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{6}
}

//离开房间返回，当房间有人推出时，也会向其他人推送这个协议
//cmd:10007
type S_LEAVE_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc  bool   `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`   //是否成功;
	ErrMess string `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"` //错误信息;
}

func (x *S_LEAVE_ROOM) Reset() {
	*x = S_LEAVE_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_LEAVE_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_LEAVE_ROOM) ProtoMessage() {}

func (x *S_LEAVE_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_LEAVE_ROOM.ProtoReflect.Descriptor instead.
func (*S_LEAVE_ROOM) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{7}
}

func (x *S_LEAVE_ROOM) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_LEAVE_ROOM) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

//选择角色请求
//cmd:20012
type C_CHOOSE_CHARACTER struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CterTempId uint32 `protobuf:"varint,1,opt,name=cter_temp_id,json=cterTempId,proto3" json:"cter_temp_id,omitempty"` //选择的角色id
}

func (x *C_CHOOSE_CHARACTER) Reset() {
	*x = C_CHOOSE_CHARACTER{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_CHOOSE_CHARACTER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_CHOOSE_CHARACTER) ProtoMessage() {}

func (x *C_CHOOSE_CHARACTER) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_CHOOSE_CHARACTER.ProtoReflect.Descriptor instead.
func (*C_CHOOSE_CHARACTER) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{8}
}

func (x *C_CHOOSE_CHARACTER) GetCterTempId() uint32 {
	if x != nil {
		return x.CterTempId
	}
	return 0
}

//选择角色返回
//cmd:10014
type S_CHOOSE_CHARACTER struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc  bool   `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`   //是否成功;
	ErrMess string `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"` //错误信息;
}

func (x *S_CHOOSE_CHARACTER) Reset() {
	*x = S_CHOOSE_CHARACTER{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_CHOOSE_CHARACTER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_CHOOSE_CHARACTER) ProtoMessage() {}

func (x *S_CHOOSE_CHARACTER) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_CHOOSE_CHARACTER.ProtoReflect.Descriptor instead.
func (*S_CHOOSE_CHARACTER) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{9}
}

func (x *S_CHOOSE_CHARACTER) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_CHOOSE_CHARACTER) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

//选择角色推送
//cmd:10019
type S_CHOOSE_CHARACTER_NOTICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               //玩家id;
	CterTempId uint32 `protobuf:"varint,2,opt,name=cter_temp_id,json=cterTempId,proto3" json:"cter_temp_id,omitempty"` //选择的角色id
}

func (x *S_CHOOSE_CHARACTER_NOTICE) Reset() {
	*x = S_CHOOSE_CHARACTER_NOTICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_CHOOSE_CHARACTER_NOTICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_CHOOSE_CHARACTER_NOTICE) ProtoMessage() {}

func (x *S_CHOOSE_CHARACTER_NOTICE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_CHOOSE_CHARACTER_NOTICE.ProtoReflect.Descriptor instead.
func (*S_CHOOSE_CHARACTER_NOTICE) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{10}
}

func (x *S_CHOOSE_CHARACTER_NOTICE) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S_CHOOSE_CHARACTER_NOTICE) GetCterTempId() uint32 {
	if x != nil {
		return x.CterTempId
	}
	return 0
}

//选择技能
//cmd:20014
type C_CHOOSE_SKILL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skills []uint32 `protobuf:"varint,1,rep,packed,name=skills,proto3" json:"skills,omitempty"` //选择的角色的技能
}

func (x *C_CHOOSE_SKILL) Reset() {
	*x = C_CHOOSE_SKILL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_CHOOSE_SKILL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_CHOOSE_SKILL) ProtoMessage() {}

func (x *C_CHOOSE_SKILL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_CHOOSE_SKILL.ProtoReflect.Descriptor instead.
func (*C_CHOOSE_SKILL) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{11}
}

func (x *C_CHOOSE_SKILL) GetSkills() []uint32 {
	if x != nil {
		return x.Skills
	}
	return nil
}

//选择技能返回
//cmd:10020
type S_CHOOSE_SKILL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc  bool     `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`   //是否成功;
	ErrMess string   `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"` //错误信息;
	Skills  []uint32 `protobuf:"varint,3,rep,packed,name=skills,proto3" json:"skills,omitempty"`          //选择的角色的技能
}

func (x *S_CHOOSE_SKILL) Reset() {
	*x = S_CHOOSE_SKILL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_CHOOSE_SKILL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_CHOOSE_SKILL) ProtoMessage() {}

func (x *S_CHOOSE_SKILL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_CHOOSE_SKILL.ProtoReflect.Descriptor instead.
func (*S_CHOOSE_SKILL) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{12}
}

func (x *S_CHOOSE_SKILL) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_CHOOSE_SKILL) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

func (x *S_CHOOSE_SKILL) GetSkills() []uint32 {
	if x != nil {
		return x.Skills
	}
	return nil
}

//T人请求
//cmd:20005
type C_KICK_MEMBER struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId uint32 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` //要T掉的玩家目标id
}

func (x *C_KICK_MEMBER) Reset() {
	*x = C_KICK_MEMBER{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_KICK_MEMBER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_KICK_MEMBER) ProtoMessage() {}

func (x *C_KICK_MEMBER) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_KICK_MEMBER.ProtoReflect.Descriptor instead.
func (*C_KICK_MEMBER) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{13}
}

func (x *C_KICK_MEMBER) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

//T人返回
//cmd:10013
type S_KICK_MEMBER struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc  bool   `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`   //是否成功;
	ErrMess string `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"` //错误信息;
}

func (x *S_KICK_MEMBER) Reset() {
	*x = S_KICK_MEMBER{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_KICK_MEMBER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_KICK_MEMBER) ProtoMessage() {}

func (x *S_KICK_MEMBER) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_KICK_MEMBER.ProtoReflect.Descriptor instead.
func (*S_KICK_MEMBER) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{14}
}

func (x *S_KICK_MEMBER) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_KICK_MEMBER) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

//换队伍
//cmd:20006
type C_CHANGE_TEAM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetTeamId uint32 `protobuf:"varint,1,opt,name=target_team_id,json=targetTeamId,proto3" json:"target_team_id,omitempty"` //想要换的队伍目标id
}

func (x *C_CHANGE_TEAM) Reset() {
	*x = C_CHANGE_TEAM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_CHANGE_TEAM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_CHANGE_TEAM) ProtoMessage() {}

func (x *C_CHANGE_TEAM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_CHANGE_TEAM.ProtoReflect.Descriptor instead.
func (*C_CHANGE_TEAM) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{15}
}

func (x *C_CHANGE_TEAM) GetTargetTeamId() uint32 {
	if x != nil {
		return x.TargetTeamId
	}
	return 0
}

//换队伍通知
//cmd:10009
type S_CHANGE_TEAM_NOTICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` //玩家id
	TeamId uint32 `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` //现在的队伍id
}

func (x *S_CHANGE_TEAM_NOTICE) Reset() {
	*x = S_CHANGE_TEAM_NOTICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_CHANGE_TEAM_NOTICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_CHANGE_TEAM_NOTICE) ProtoMessage() {}

func (x *S_CHANGE_TEAM_NOTICE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_CHANGE_TEAM_NOTICE.ProtoReflect.Descriptor instead.
func (*S_CHANGE_TEAM_NOTICE) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{16}
}

func (x *S_CHANGE_TEAM_NOTICE) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S_CHANGE_TEAM_NOTICE) GetTeamId() uint32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

//准备与取消准备
//cmd:20007
type C_PREPARE_CANCEL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prepare bool `protobuf:"varint,1,opt,name=prepare,proto3" json:"prepare,omitempty"` //true代表准备，false代表取消准备
}

func (x *C_PREPARE_CANCEL) Reset() {
	*x = C_PREPARE_CANCEL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_PREPARE_CANCEL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_PREPARE_CANCEL) ProtoMessage() {}

func (x *C_PREPARE_CANCEL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_PREPARE_CANCEL.ProtoReflect.Descriptor instead.
func (*C_PREPARE_CANCEL) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{17}
}

func (x *C_PREPARE_CANCEL) GetPrepare() bool {
	if x != nil {
		return x.Prepare
	}
	return false
}

//准备与取消返回
//cmd:10010
type S_PREPARE_CANCEL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc  bool   `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`   //是否成功;
	ErrMess string `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"` //错误信息;
}

func (x *S_PREPARE_CANCEL) Reset() {
	*x = S_PREPARE_CANCEL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_PREPARE_CANCEL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_PREPARE_CANCEL) ProtoMessage() {}

func (x *S_PREPARE_CANCEL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_PREPARE_CANCEL.ProtoReflect.Descriptor instead.
func (*S_PREPARE_CANCEL) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{18}
}

func (x *S_PREPARE_CANCEL) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_PREPARE_CANCEL) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

//准备与取消通知
//cmd:10021
type S_PREPARE_CANCEL_NOTICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Prepare bool   `protobuf:"varint,2,opt,name=prepare,proto3" json:"prepare,omitempty"` //true代表准备，false代表取消准备
}

func (x *S_PREPARE_CANCEL_NOTICE) Reset() {
	*x = S_PREPARE_CANCEL_NOTICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_PREPARE_CANCEL_NOTICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_PREPARE_CANCEL_NOTICE) ProtoMessage() {}

func (x *S_PREPARE_CANCEL_NOTICE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_PREPARE_CANCEL_NOTICE.ProtoReflect.Descriptor instead.
func (*S_PREPARE_CANCEL_NOTICE) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{19}
}

func (x *S_PREPARE_CANCEL_NOTICE) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S_PREPARE_CANCEL_NOTICE) GetPrepare() bool {
	if x != nil {
		return x.Prepare
	}
	return false
}

//开始游戏
//cmd:20008
type C_START struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C_START) Reset() {
	*x = C_START{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_START) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_START) ProtoMessage() {}

func (x *C_START) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_START.ProtoReflect.Descriptor instead.
func (*C_START) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{20}
}

//开始游戏返回
//cmd:10008
type S_START struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc  bool   `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`   //是否成功;
	ErrMess string `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"` //错误信息;
}

func (x *S_START) Reset() {
	*x = S_START{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_START) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_START) ProtoMessage() {}

func (x *S_START) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_START.ProtoReflect.Descriptor instead.
func (*S_START) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{21}
}

func (x *S_START) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_START) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

//房间新成员推送消息
//cmd:10012
type S_ROOM_ADD_MEMBER_NOTICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  uint32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`  //成员位置
	Member *MemberPt `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"` //成员数据
}

func (x *S_ROOM_ADD_MEMBER_NOTICE) Reset() {
	*x = S_ROOM_ADD_MEMBER_NOTICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_ROOM_ADD_MEMBER_NOTICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_ROOM_ADD_MEMBER_NOTICE) ProtoMessage() {}

func (x *S_ROOM_ADD_MEMBER_NOTICE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_ROOM_ADD_MEMBER_NOTICE.ProtoReflect.Descriptor instead.
func (*S_ROOM_ADD_MEMBER_NOTICE) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{22}
}

func (x *S_ROOM_ADD_MEMBER_NOTICE) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *S_ROOM_ADD_MEMBER_NOTICE) GetMember() *MemberPt {
	if x != nil {
		return x.Member
	}
	return nil
}

//房间变动推送
//cmd:10015
type S_ROOM_NOTICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId uint32         `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` //房主ID
	Setting *RoomSettingPt `protobuf:"bytes,2,opt,name=setting,proto3" json:"setting,omitempty"`                 //房间设置
}

func (x *S_ROOM_NOTICE) Reset() {
	*x = S_ROOM_NOTICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_ROOM_NOTICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_ROOM_NOTICE) ProtoMessage() {}

func (x *S_ROOM_NOTICE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_ROOM_NOTICE.ProtoReflect.Descriptor instead.
func (*S_ROOM_NOTICE) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{23}
}

func (x *S_ROOM_NOTICE) GetOwnerId() uint32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *S_ROOM_NOTICE) GetSetting() *RoomSettingPt {
	if x != nil {
		return x.Setting
	}
	return nil
}

//表情请求
//cmd:20013
type C_EMOJI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmojiId uint32 `protobuf:"varint,1,opt,name=emoji_id,json=emojiId,proto3" json:"emoji_id,omitempty"` //表情符号id
}

func (x *C_EMOJI) Reset() {
	*x = C_EMOJI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_EMOJI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_EMOJI) ProtoMessage() {}

func (x *C_EMOJI) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_EMOJI.ProtoReflect.Descriptor instead.
func (*C_EMOJI) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{24}
}

func (x *C_EMOJI) GetEmojiId() uint32 {
	if x != nil {
		return x.EmojiId
	}
	return 0
}

//表情返回
//cmd:10016
type S_EMOJI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc  bool   `protobuf:"varint,1,opt,name=is_succ,json=isSucc,proto3" json:"is_succ,omitempty"`   //是否成功;
	ErrMess string `protobuf:"bytes,2,opt,name=err_mess,json=errMess,proto3" json:"err_mess,omitempty"` //错误信息;
}

func (x *S_EMOJI) Reset() {
	*x = S_EMOJI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_EMOJI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_EMOJI) ProtoMessage() {}

func (x *S_EMOJI) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_EMOJI.ProtoReflect.Descriptor instead.
func (*S_EMOJI) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{25}
}

func (x *S_EMOJI) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *S_EMOJI) GetErrMess() string {
	if x != nil {
		return x.ErrMess
	}
	return ""
}

//表情推送
//cmd:10017
type S_EMOJI_NOTICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    //玩家id
	EmojiId uint32 `protobuf:"varint,2,opt,name=emoji_id,json=emojiId,proto3" json:"emoji_id,omitempty"` //表情id
}

func (x *S_EMOJI_NOTICE) Reset() {
	*x = S_EMOJI_NOTICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_EMOJI_NOTICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_EMOJI_NOTICE) ProtoMessage() {}

func (x *S_EMOJI_NOTICE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_EMOJI_NOTICE.ProtoReflect.Descriptor instead.
func (*S_EMOJI_NOTICE) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{26}
}

func (x *S_EMOJI_NOTICE) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S_EMOJI_NOTICE) GetEmojiId() uint32 {
	if x != nil {
		return x.EmojiId
	}
	return 0
}

//房间成员推送消息
//cmd:10018
type S_ROOM_MEMBER_LEAVE_NOTICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoticeType uint32 `protobuf:"varint,1,opt,name=notice_type,json=noticeType,proto3" json:"notice_type,omitempty"` //类型 1:自己离开 2:被T出去
	UserId     uint32 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             //离开的玩家id
}

func (x *S_ROOM_MEMBER_LEAVE_NOTICE) Reset() {
	*x = S_ROOM_MEMBER_LEAVE_NOTICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_ROOM_MEMBER_LEAVE_NOTICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_ROOM_MEMBER_LEAVE_NOTICE) ProtoMessage() {}

func (x *S_ROOM_MEMBER_LEAVE_NOTICE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_ROOM_MEMBER_LEAVE_NOTICE.ProtoReflect.Descriptor instead.
func (*S_ROOM_MEMBER_LEAVE_NOTICE) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{27}
}

func (x *S_ROOM_MEMBER_LEAVE_NOTICE) GetNoticeType() uint32 {
	if x != nil {
		return x.NoticeType
	}
	return 0
}

func (x *S_ROOM_MEMBER_LEAVE_NOTICE) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

//匹配成功通知
//cmd:10029
type S_MATCH_SUCCESS_NOTICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` //点击去人进入房间人的数量
}

func (x *S_MATCH_SUCCESS_NOTICE) Reset() {
	*x = S_MATCH_SUCCESS_NOTICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_MATCH_SUCCESS_NOTICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_MATCH_SUCCESS_NOTICE) ProtoMessage() {}

func (x *S_MATCH_SUCCESS_NOTICE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_MATCH_SUCCESS_NOTICE.ProtoReflect.Descriptor instead.
func (*S_MATCH_SUCCESS_NOTICE) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{28}
}

func (x *S_MATCH_SUCCESS_NOTICE) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

//确认进入房间  此消息没有服务器不返回
//cmd:20015
type C_CONFIRM_INTO_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Confirm bool `protobuf:"varint,1,opt,name=confirm,proto3" json:"confirm,omitempty"` //false为不进入房间，true为确定进入房间
}

func (x *C_CONFIRM_INTO_ROOM) Reset() {
	*x = C_CONFIRM_INTO_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_CONFIRM_INTO_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_CONFIRM_INTO_ROOM) ProtoMessage() {}

func (x *C_CONFIRM_INTO_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_CONFIRM_INTO_ROOM.ProtoReflect.Descriptor instead.
func (*C_CONFIRM_INTO_ROOM) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{29}
}

func (x *C_CONFIRM_INTO_ROOM) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

//确认进入房间推送
//cmd:10061
type S_CONFIRM_INTO_ROOM_NOTICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` //点击去人进入房间人的数量
}

func (x *S_CONFIRM_INTO_ROOM_NOTICE) Reset() {
	*x = S_CONFIRM_INTO_ROOM_NOTICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_CONFIRM_INTO_ROOM_NOTICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_CONFIRM_INTO_ROOM_NOTICE) ProtoMessage() {}

func (x *S_CONFIRM_INTO_ROOM_NOTICE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_CONFIRM_INTO_ROOM_NOTICE.ProtoReflect.Descriptor instead.
func (*S_CONFIRM_INTO_ROOM_NOTICE) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{30}
}

func (x *S_CONFIRM_INTO_ROOM_NOTICE) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

//进入房间取消通知  此消息没有任何数据内容
//cmd:10028
type S_INTO_ROOM_CANCEL_NOTICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S_INTO_ROOM_CANCEL_NOTICE) Reset() {
	*x = S_INTO_ROOM_CANCEL_NOTICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_INTO_ROOM_CANCEL_NOTICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_INTO_ROOM_CANCEL_NOTICE) ProtoMessage() {}

func (x *S_INTO_ROOM_CANCEL_NOTICE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_INTO_ROOM_CANCEL_NOTICE.ProtoReflect.Descriptor instead.
func (*S_INTO_ROOM_CANCEL_NOTICE) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{31}
}

//取消匹配请求指令
//cmd:20016
type C_CANCEL_SEARCH struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C_CANCEL_SEARCH) Reset() {
	*x = C_CANCEL_SEARCH{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_CANCEL_SEARCH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_CANCEL_SEARCH) ProtoMessage() {}

func (x *C_CANCEL_SEARCH) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_CANCEL_SEARCH.ProtoReflect.Descriptor instead.
func (*C_CANCEL_SEARCH) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{32}
}

//取消匹配返回指令
//cmd:10060
type S_CANCEL_SEARCH struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S_CANCEL_SEARCH) Reset() {
	*x = S_CANCEL_SEARCH{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_CANCEL_SEARCH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_CANCEL_SEARCH) ProtoMessage() {}

func (x *S_CANCEL_SEARCH) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_CANCEL_SEARCH.ProtoReflect.Descriptor instead.
func (*S_CANCEL_SEARCH) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{33}
}

//匹配惩罚更新推送
//cmd:10103
type S_PUNISH_MATCH_NOTICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint32         `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               //玩家id
	PunishMatch *PunishMatchPt `protobuf:"bytes,2,opt,name=punish_match,json=punishMatch,proto3" json:"punish_match,omitempty"` //匹配惩罚
}

func (x *S_PUNISH_MATCH_NOTICE) Reset() {
	*x = S_PUNISH_MATCH_NOTICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_PUNISH_MATCH_NOTICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_PUNISH_MATCH_NOTICE) ProtoMessage() {}

func (x *S_PUNISH_MATCH_NOTICE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_PUNISH_MATCH_NOTICE.ProtoReflect.Descriptor instead.
func (*S_PUNISH_MATCH_NOTICE) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{34}
}

func (x *S_PUNISH_MATCH_NOTICE) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S_PUNISH_MATCH_NOTICE) GetPunishMatch() *PunishMatchPt {
	if x != nil {
		return x.PunishMatch
	}
	return nil
}

//选择ai角色请求
//cmd:20018
type C_CHOICE_AI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index       uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                                  //对应的位置下标
	RobotTempId uint32 `protobuf:"varint,2,opt,name=robot_temp_id,json=robotTempId,proto3" json:"robot_temp_id,omitempty"` //机器人配置id
}

func (x *C_CHOICE_AI) Reset() {
	*x = C_CHOICE_AI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_CHOICE_AI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_CHOICE_AI) ProtoMessage() {}

func (x *C_CHOICE_AI) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_CHOICE_AI.ProtoReflect.Descriptor instead.
func (*C_CHOICE_AI) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{35}
}

func (x *C_CHOICE_AI) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *C_CHOICE_AI) GetRobotTempId() uint32 {
	if x != nil {
		return x.RobotTempId
	}
	return 0
}

//选择ai角色通知
//cmd:10201
type S_CHOICE_AI_NOTICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index       uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                                  //对应的位置下标
	RobotTempId uint32 `protobuf:"varint,2,opt,name=robot_temp_id,json=robotTempId,proto3" json:"robot_temp_id,omitempty"` //对应AI的角色
	UserId      uint32 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  //对应AI的角色
}

func (x *S_CHOICE_AI_NOTICE) Reset() {
	*x = S_CHOICE_AI_NOTICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_room_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_CHOICE_AI_NOTICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_CHOICE_AI_NOTICE) ProtoMessage() {}

func (x *S_CHOICE_AI_NOTICE) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_room_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_CHOICE_AI_NOTICE.ProtoReflect.Descriptor instead.
func (*S_CHOICE_AI_NOTICE) Descriptor() ([]byte, []int) {
	return file_proto_files_room_proto_rawDescGZIP(), []int{36}
}

func (x *S_CHOICE_AI_NOTICE) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *S_CHOICE_AI_NOTICE) GetRobotTempId() uint32 {
	if x != nil {
		return x.RobotTempId
	}
	return 0
}

func (x *S_CHOICE_AI_NOTICE) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_proto_files_room_proto protoreflect.FileDescriptor

var file_proto_files_room_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x1a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x0d, 0x43, 0x5f, 0x43, 0x52,
	0x45, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x74, 0x52, 0x07,
	0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x43, 0x0a, 0x0b, 0x43, 0x5f, 0x4a, 0x4f, 0x49,
	0x4e, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2c, 0x0a, 0x0d,
	0x43, 0x5f, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x22, 0x7b, 0x0a, 0x06, 0x53, 0x5f,
	0x52, 0x4f, 0x4f, 0x4d, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x12, 0x19, 0x0a,
	0x08, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x50,
	0x74, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x41, 0x0a, 0x0e, 0x43, 0x5f, 0x52, 0x4f, 0x4f,
	0x4d, 0x5f, 0x53, 0x45, 0x54, 0x54, 0x49, 0x4e, 0x47, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x65, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x44, 0x0a, 0x0e, 0x53, 0x5f,
	0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x53, 0x45, 0x54, 0x54, 0x49, 0x4e, 0x47, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x53, 0x75, 0x63, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x5f, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x4d,
	0x22, 0x42, 0x0a, 0x0c, 0x53, 0x5f, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x4d,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x22, 0x36, 0x0a, 0x12, 0x43, 0x5f, 0x43, 0x48, 0x4f, 0x4f, 0x53, 0x45,
	0x5f, 0x43, 0x48, 0x41, 0x52, 0x41, 0x43, 0x54, 0x45, 0x52, 0x12, 0x20, 0x0a, 0x0c, 0x63, 0x74,
	0x65, 0x72, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x63, 0x74, 0x65, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x12,
	0x53, 0x5f, 0x43, 0x48, 0x4f, 0x4f, 0x53, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x52, 0x41, 0x43, 0x54,
	0x45, 0x52, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x72, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x22, 0x56, 0x0a, 0x19, 0x53, 0x5f, 0x43, 0x48, 0x4f, 0x4f,
	0x53, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x52, 0x41, 0x43, 0x54, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54,
	0x49, 0x43, 0x45, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c,
	0x63, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x63, 0x74, 0x65, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x49, 0x64, 0x22, 0x28,
	0x0a, 0x0e, 0x43, 0x5f, 0x43, 0x48, 0x4f, 0x4f, 0x53, 0x45, 0x5f, 0x53, 0x4b, 0x49, 0x4c, 0x4c,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x22, 0x5c, 0x0a, 0x0e, 0x53, 0x5f, 0x43, 0x48,
	0x4f, 0x4f, 0x53, 0x45, 0x5f, 0x53, 0x4b, 0x49, 0x4c, 0x4c, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73,
	0x5f, 0x73, 0x75, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53,
	0x75, 0x63, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x22, 0x2c, 0x0a, 0x0d, 0x43, 0x5f, 0x4b, 0x49, 0x43, 0x4b,
	0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x0d, 0x53, 0x5f, 0x4b, 0x49, 0x43, 0x4b, 0x5f, 0x4d,
	0x45, 0x4d, 0x42, 0x45, 0x52, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x22, 0x35, 0x0a, 0x0d, 0x43, 0x5f, 0x43,
	0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x54, 0x45, 0x41, 0x4d, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x64,
	0x22, 0x48, 0x0a, 0x14, 0x53, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x54, 0x45, 0x41,
	0x4d, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x10, 0x43, 0x5f,
	0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x22, 0x46, 0x0a, 0x10, 0x53, 0x5f, 0x50, 0x52,
	0x45, 0x50, 0x41, 0x52, 0x45, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x53, 0x75, 0x63, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x22, 0x4c, 0x0a, 0x17, 0x53, 0x5f, 0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x5f, 0x43, 0x41,
	0x4e, 0x43, 0x45, 0x4c, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x22, 0x09,
	0x0a, 0x07, 0x43, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x22, 0x3d, 0x0a, 0x07, 0x53, 0x5f, 0x53,
	0x54, 0x41, 0x52, 0x54, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x12, 0x19, 0x0a,
	0x08, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x22, 0x5a, 0x0a, 0x18, 0x53, 0x5f, 0x52, 0x4f,
	0x4f, 0x4d, 0x5f, 0x41, 0x44, 0x44, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x4e, 0x4f,
	0x54, 0x49, 0x43, 0x45, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x28, 0x0a, 0x06, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x74, 0x52, 0x06, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x0d, 0x53, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x4e,
	0x4f, 0x54, 0x49, 0x43, 0x45, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x2f, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x74, 0x52, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x22, 0x24, 0x0a, 0x07, 0x43, 0x5f, 0x45, 0x4d, 0x4f, 0x4a, 0x49, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x07, 0x53, 0x5f, 0x45, 0x4d, 0x4f,
	0x4a, 0x49, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x72, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x22, 0x44, 0x0a, 0x0e, 0x53, 0x5f, 0x45, 0x4d, 0x4f, 0x4a,
	0x49, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x49, 0x64, 0x22, 0x56, 0x0a, 0x1a,
	0x53, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x4c, 0x45,
	0x41, 0x56, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x16, 0x53, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2f, 0x0a, 0x13, 0x43, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x52,
	0x4d, 0x5f, 0x49, 0x4e, 0x54, 0x4f, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x22, 0x32, 0x0a, 0x1a, 0x53, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49,
	0x52, 0x4d, 0x5f, 0x49, 0x4e, 0x54, 0x4f, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x4e, 0x4f, 0x54,
	0x49, 0x43, 0x45, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x53, 0x5f, 0x49,
	0x4e, 0x54, 0x4f, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x5f,
	0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x5f, 0x43, 0x41, 0x4e, 0x43,
	0x45, 0x4c, 0x5f, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x5f, 0x43,
	0x41, 0x4e, 0x43, 0x45, 0x4c, 0x5f, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x22, 0x6a, 0x0a, 0x15,
	0x53, 0x5f, 0x50, 0x55, 0x4e, 0x49, 0x53, 0x48, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x4e,
	0x4f, 0x54, 0x49, 0x43, 0x45, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38,
	0x0a, 0x0c, 0x70, 0x75, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x75,
	0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x74, 0x52, 0x0b, 0x70, 0x75, 0x6e,
	0x69, 0x73, 0x68, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x47, 0x0a, 0x0b, 0x43, 0x5f, 0x43, 0x48,
	0x4f, 0x49, 0x43, 0x45, 0x5f, 0x41, 0x49, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x22, 0x0a,
	0x0d, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x49,
	0x64, 0x22, 0x67, 0x0a, 0x12, 0x53, 0x5f, 0x43, 0x48, 0x4f, 0x49, 0x43, 0x45, 0x5f, 0x41, 0x49,
	0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x22, 0x0a,
	0x0d, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_files_room_proto_rawDescOnce sync.Once
	file_proto_files_room_proto_rawDescData = file_proto_files_room_proto_rawDesc
)

func file_proto_files_room_proto_rawDescGZIP() []byte {
	file_proto_files_room_proto_rawDescOnce.Do(func() {
		file_proto_files_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_room_proto_rawDescData)
	})
	return file_proto_files_room_proto_rawDescData
}

var file_proto_files_room_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_files_room_proto_goTypes = []interface{}{
	(*C_CREATE_ROOM)(nil),              // 0: protos.C_CREATE_ROOM
	(*C_JOIN_ROOM)(nil),                // 1: protos.C_JOIN_ROOM
	(*C_SEARCH_ROOM)(nil),              // 2: protos.C_SEARCH_ROOM
	(*S_ROOM)(nil),                     // 3: protos.S_ROOM
	(*C_ROOM_SETTING)(nil),             // 4: protos.C_ROOM_SETTING
	(*S_ROOM_SETTING)(nil),             // 5: protos.S_ROOM_SETTING
	(*C_LEAVE_ROOM)(nil),               // 6: protos.C_LEAVE_ROOM
	(*S_LEAVE_ROOM)(nil),               // 7: protos.S_LEAVE_ROOM
	(*C_CHOOSE_CHARACTER)(nil),         // 8: protos.C_CHOOSE_CHARACTER
	(*S_CHOOSE_CHARACTER)(nil),         // 9: protos.S_CHOOSE_CHARACTER
	(*S_CHOOSE_CHARACTER_NOTICE)(nil),  // 10: protos.S_CHOOSE_CHARACTER_NOTICE
	(*C_CHOOSE_SKILL)(nil),             // 11: protos.C_CHOOSE_SKILL
	(*S_CHOOSE_SKILL)(nil),             // 12: protos.S_CHOOSE_SKILL
	(*C_KICK_MEMBER)(nil),              // 13: protos.C_KICK_MEMBER
	(*S_KICK_MEMBER)(nil),              // 14: protos.S_KICK_MEMBER
	(*C_CHANGE_TEAM)(nil),              // 15: protos.C_CHANGE_TEAM
	(*S_CHANGE_TEAM_NOTICE)(nil),       // 16: protos.S_CHANGE_TEAM_NOTICE
	(*C_PREPARE_CANCEL)(nil),           // 17: protos.C_PREPARE_CANCEL
	(*S_PREPARE_CANCEL)(nil),           // 18: protos.S_PREPARE_CANCEL
	(*S_PREPARE_CANCEL_NOTICE)(nil),    // 19: protos.S_PREPARE_CANCEL_NOTICE
	(*C_START)(nil),                    // 20: protos.C_START
	(*S_START)(nil),                    // 21: protos.S_START
	(*S_ROOM_ADD_MEMBER_NOTICE)(nil),   // 22: protos.S_ROOM_ADD_MEMBER_NOTICE
	(*S_ROOM_NOTICE)(nil),              // 23: protos.S_ROOM_NOTICE
	(*C_EMOJI)(nil),                    // 24: protos.C_EMOJI
	(*S_EMOJI)(nil),                    // 25: protos.S_EMOJI
	(*S_EMOJI_NOTICE)(nil),             // 26: protos.S_EMOJI_NOTICE
	(*S_ROOM_MEMBER_LEAVE_NOTICE)(nil), // 27: protos.S_ROOM_MEMBER_LEAVE_NOTICE
	(*S_MATCH_SUCCESS_NOTICE)(nil),     // 28: protos.S_MATCH_SUCCESS_NOTICE
	(*C_CONFIRM_INTO_ROOM)(nil),        // 29: protos.C_CONFIRM_INTO_ROOM
	(*S_CONFIRM_INTO_ROOM_NOTICE)(nil), // 30: protos.S_CONFIRM_INTO_ROOM_NOTICE
	(*S_INTO_ROOM_CANCEL_NOTICE)(nil),  // 31: protos.S_INTO_ROOM_CANCEL_NOTICE
	(*C_CANCEL_SEARCH)(nil),            // 32: protos.C_CANCEL_SEARCH
	(*S_CANCEL_SEARCH)(nil),            // 33: protos.S_CANCEL_SEARCH
	(*S_PUNISH_MATCH_NOTICE)(nil),      // 34: protos.S_PUNISH_MATCH_NOTICE
	(*C_CHOICE_AI)(nil),                // 35: protos.C_CHOICE_AI
	(*S_CHOICE_AI_NOTICE)(nil),         // 36: protos.S_CHOICE_AI_NOTICE
	(*RoomSettingPt)(nil),              // 37: protos.RoomSettingPt
	(*RoomPt)(nil),                     // 38: protos.RoomPt
	(*MemberPt)(nil),                   // 39: protos.MemberPt
	(*PunishMatchPt)(nil),              // 40: protos.PunishMatchPt
}
var file_proto_files_room_proto_depIdxs = []int32{
	37, // 0: protos.C_CREATE_ROOM.setting:type_name -> protos.RoomSettingPt
	38, // 1: protos.S_ROOM.room:type_name -> protos.RoomPt
	39, // 2: protos.S_ROOM_ADD_MEMBER_NOTICE.member:type_name -> protos.MemberPt
	37, // 3: protos.S_ROOM_NOTICE.setting:type_name -> protos.RoomSettingPt
	40, // 4: protos.S_PUNISH_MATCH_NOTICE.punish_match:type_name -> protos.PunishMatchPt
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_files_room_proto_init() }
func file_proto_files_room_proto_init() {
	if File_proto_files_room_proto != nil {
		return
	}
	file_proto_files_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_files_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_CREATE_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_JOIN_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_SEARCH_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_ROOM_SETTING); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_ROOM_SETTING); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_LEAVE_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_LEAVE_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_CHOOSE_CHARACTER); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_CHOOSE_CHARACTER); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_CHOOSE_CHARACTER_NOTICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_CHOOSE_SKILL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_CHOOSE_SKILL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_KICK_MEMBER); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_KICK_MEMBER); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_CHANGE_TEAM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_CHANGE_TEAM_NOTICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_PREPARE_CANCEL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_PREPARE_CANCEL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_PREPARE_CANCEL_NOTICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_START); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_START); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_ROOM_ADD_MEMBER_NOTICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_ROOM_NOTICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_EMOJI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_EMOJI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_EMOJI_NOTICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_ROOM_MEMBER_LEAVE_NOTICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_MATCH_SUCCESS_NOTICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_CONFIRM_INTO_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_CONFIRM_INTO_ROOM_NOTICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_INTO_ROOM_CANCEL_NOTICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_CANCEL_SEARCH); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_CANCEL_SEARCH); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_PUNISH_MATCH_NOTICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_CHOICE_AI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_room_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_CHOICE_AI_NOTICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_files_room_proto_goTypes,
		DependencyIndexes: file_proto_files_room_proto_depIdxs,
		MessageInfos:      file_proto_files_room_proto_msgTypes,
	}.Build()
	File_proto_files_room_proto = out.File
	file_proto_files_room_proto_rawDesc = nil
	file_proto_files_room_proto_goTypes = nil
	file_proto_files_room_proto_depIdxs = nil
}
