// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.7.1
// source: proto_files/server_protocol.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

///房间服到战斗服-战斗开始
type R_B_START struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomPt *RoomPt `protobuf:"bytes,1,opt,name=room_pt,json=roomPt,proto3" json:"room_pt,omitempty"` //房间数据
}

func (x *R_B_START) Reset() {
	*x = R_B_START{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_server_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *R_B_START) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*R_B_START) ProtoMessage() {}

func (x *R_B_START) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_server_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use R_B_START.ProtoReflect.Descriptor instead.
func (*R_B_START) Descriptor() ([]byte, []int) {
	return file_proto_files_server_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *R_B_START) GetRoomPt() *RoomPt {
	if x != nil {
		return x.RoomPt
	}
	return nil
}

///游戏服务器发给房间服务器，创建房间
type G_R_CREATE_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType uint32          `protobuf:"varint,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"` //房间类型
	Pbp      *PlayerBattlePt `protobuf:"bytes,2,opt,name=pbp,proto3" json:"pbp,omitempty"`                            //玩家房间需要的数据
	Setting  *RoomSettingPt  `protobuf:"bytes,3,opt,name=setting,proto3" json:"setting,omitempty"`                    //房间设置,只有自定义房间的时候需要传，其他房间类型不要传
}

func (x *G_R_CREATE_ROOM) Reset() {
	*x = G_R_CREATE_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_server_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G_R_CREATE_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G_R_CREATE_ROOM) ProtoMessage() {}

func (x *G_R_CREATE_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_server_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G_R_CREATE_ROOM.ProtoReflect.Descriptor instead.
func (*G_R_CREATE_ROOM) Descriptor() ([]byte, []int) {
	return file_proto_files_server_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *G_R_CREATE_ROOM) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *G_R_CREATE_ROOM) GetPbp() *PlayerBattlePt {
	if x != nil {
		return x.Pbp
	}
	return nil
}

func (x *G_R_CREATE_ROOM) GetSetting() *RoomSettingPt {
	if x != nil {
		return x.Setting
	}
	return nil
}

///游戏服务器发给房间服务器，加入房间
type G_R_JOIN_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   uint32          `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`       //房间id
	RoomType uint32          `protobuf:"varint,2,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"` //房间类型
	Pbp      *PlayerBattlePt `protobuf:"bytes,3,opt,name=pbp,proto3" json:"pbp,omitempty"`                            //玩家房间需要的数据
}

func (x *G_R_JOIN_ROOM) Reset() {
	*x = G_R_JOIN_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_server_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G_R_JOIN_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G_R_JOIN_ROOM) ProtoMessage() {}

func (x *G_R_JOIN_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_server_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G_R_JOIN_ROOM.ProtoReflect.Descriptor instead.
func (*G_R_JOIN_ROOM) Descriptor() ([]byte, []int) {
	return file_proto_files_server_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *G_R_JOIN_ROOM) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *G_R_JOIN_ROOM) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *G_R_JOIN_ROOM) GetPbp() *PlayerBattlePt {
	if x != nil {
		return x.Pbp
	}
	return nil
}

///游戏服务器发给房间服务器，快速开始
type G_R_SEARCH_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType uint32          `protobuf:"varint,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"` //模式
	Pbp      *PlayerBattlePt `protobuf:"bytes,2,opt,name=pbp,proto3" json:"pbp,omitempty"`                            //玩家房间需要的数据
}

func (x *G_R_SEARCH_ROOM) Reset() {
	*x = G_R_SEARCH_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_server_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G_R_SEARCH_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G_R_SEARCH_ROOM) ProtoMessage() {}

func (x *G_R_SEARCH_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_server_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G_R_SEARCH_ROOM.ProtoReflect.Descriptor instead.
func (*G_R_SEARCH_ROOM) Descriptor() ([]byte, []int) {
	return file_proto_files_server_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *G_R_SEARCH_ROOM) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *G_R_SEARCH_ROOM) GetPbp() *PlayerBattlePt {
	if x != nil {
		return x.Pbp
	}
	return nil
}

///战斗服结算转发消息，发给游戏服，排行榜服
type B_S_SUMMARY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType    uint32         `protobuf:"varint,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`         //房间类型
	Cters       []uint32       `protobuf:"varint,2,rep,packed,name=cters,proto3" json:"cters,omitempty"`                        //使用排名前三的角色
	SummaryData *SummaryDataPt `protobuf:"bytes,3,opt,name=summary_data,json=summaryData,proto3" json:"summary_data,omitempty"` //结算数据
}

func (x *B_S_SUMMARY) Reset() {
	*x = B_S_SUMMARY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_server_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B_S_SUMMARY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B_S_SUMMARY) ProtoMessage() {}

func (x *B_S_SUMMARY) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_server_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B_S_SUMMARY.ProtoReflect.Descriptor instead.
func (*B_S_SUMMARY) Descriptor() ([]byte, []int) {
	return file_proto_files_server_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *B_S_SUMMARY) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *B_S_SUMMARY) GetCters() []uint32 {
	if x != nil {
		return x.Cters
	}
	return nil
}

func (x *B_S_SUMMARY) GetSummaryData() *SummaryDataPt {
	if x != nil {
		return x.SummaryData
	}
	return nil
}

///游戏服务器发给房间服务器，战斗结算
type B_R_SUMMARY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType uint32 `protobuf:"varint,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"` //房间类型
	RoomId   uint32 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`       //房间id
}

func (x *B_R_SUMMARY) Reset() {
	*x = B_R_SUMMARY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_server_protocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B_R_SUMMARY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B_R_SUMMARY) ProtoMessage() {}

func (x *B_R_SUMMARY) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_server_protocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B_R_SUMMARY.ProtoReflect.Descriptor instead.
func (*B_R_SUMMARY) Descriptor() ([]byte, []int) {
	return file_proto_files_server_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *B_R_SUMMARY) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *B_R_SUMMARY) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

//玩家战斗数据封装proto
type PlayerBattlePt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint32         `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               //玩家id
	NickName    string         `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`          //玩家昵称
	Grade       uint32         `protobuf:"varint,3,opt,name=grade,proto3" json:"grade,omitempty"`                               //grade
	GradeFrame  uint32         `protobuf:"varint,4,opt,name=grade_frame,json=gradeFrame,proto3" json:"grade_frame,omitempty"`   //grade像框
	Soul        uint32         `protobuf:"varint,5,opt,name=soul,proto3" json:"soul,omitempty"`                                 //灵魂头像
	League      *LeaguePt      `protobuf:"bytes,6,opt,name=league,proto3" json:"league,omitempty"`                              //段位数据
	PunishMatch *PunishMatchPt `protobuf:"bytes,7,opt,name=punish_match,json=punishMatch,proto3" json:"punish_match,omitempty"` //匹配惩罚
	Cters       []*CharacterPt `protobuf:"bytes,8,rep,name=cters,proto3" json:"cters,omitempty"`                                //玩家解锁的角色数组
}

func (x *PlayerBattlePt) Reset() {
	*x = PlayerBattlePt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_server_protocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBattlePt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBattlePt) ProtoMessage() {}

func (x *PlayerBattlePt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_server_protocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBattlePt.ProtoReflect.Descriptor instead.
func (*PlayerBattlePt) Descriptor() ([]byte, []int) {
	return file_proto_files_server_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerBattlePt) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlayerBattlePt) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *PlayerBattlePt) GetGrade() uint32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *PlayerBattlePt) GetGradeFrame() uint32 {
	if x != nil {
		return x.GradeFrame
	}
	return 0
}

func (x *PlayerBattlePt) GetSoul() uint32 {
	if x != nil {
		return x.Soul
	}
	return 0
}

func (x *PlayerBattlePt) GetLeague() *LeaguePt {
	if x != nil {
		return x.League
	}
	return nil
}

func (x *PlayerBattlePt) GetPunishMatch() *PunishMatchPt {
	if x != nil {
		return x.PunishMatch
	}
	return nil
}

func (x *PlayerBattlePt) GetCters() []*CharacterPt {
	if x != nil {
		return x.Cters
	}
	return nil
}

///游戏服务器发给房间服务器，快速开始
type B_R_G_PUNISH_MATCH struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PunishMatch *PunishMatchPt `protobuf:"bytes,1,opt,name=punish_match,json=punishMatch,proto3" json:"punish_match,omitempty"` //战斗服和房间服同步惩罚到游戏服
}

func (x *B_R_G_PUNISH_MATCH) Reset() {
	*x = B_R_G_PUNISH_MATCH{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_server_protocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B_R_G_PUNISH_MATCH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B_R_G_PUNISH_MATCH) ProtoMessage() {}

func (x *B_R_G_PUNISH_MATCH) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_server_protocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B_R_G_PUNISH_MATCH.ProtoReflect.Descriptor instead.
func (*B_R_G_PUNISH_MATCH) Descriptor() ([]byte, []int) {
	return file_proto_files_server_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *B_R_G_PUNISH_MATCH) GetPunishMatch() *PunishMatchPt {
	if x != nil {
		return x.PunishMatch
	}
	return nil
}

///排行榜服务器同步给游戏服排行榜信息
type R_G_SYNC_RANK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *R_G_SYNC_RANK) Reset() {
	*x = R_G_SYNC_RANK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_server_protocol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *R_G_SYNC_RANK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*R_G_SYNC_RANK) ProtoMessage() {}

func (x *R_G_SYNC_RANK) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_server_protocol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use R_G_SYNC_RANK.ProtoReflect.Descriptor instead.
func (*R_G_SYNC_RANK) Descriptor() ([]byte, []int) {
	return file_proto_files_server_protocol_proto_rawDescGZIP(), []int{8}
}

///通知游戏服更新上一赛季的排行榜数据
type R_S_UPDATE_SEASON struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeasonId       int32  `protobuf:"varint,1,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`                     //赛季信息
	Round          uint32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`                                           //赛季round
	NextUpdateTime uint64 `protobuf:"varint,3,opt,name=next_update_time,json=nextUpdateTime,proto3" json:"next_update_time,omitempty"` //下次更新时间
}

func (x *R_S_UPDATE_SEASON) Reset() {
	*x = R_S_UPDATE_SEASON{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_server_protocol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *R_S_UPDATE_SEASON) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*R_S_UPDATE_SEASON) ProtoMessage() {}

func (x *R_S_UPDATE_SEASON) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_server_protocol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use R_S_UPDATE_SEASON.ProtoReflect.Descriptor instead.
func (*R_S_UPDATE_SEASON) Descriptor() ([]byte, []int) {
	return file_proto_files_server_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *R_S_UPDATE_SEASON) GetSeasonId() int32 {
	if x != nil {
		return x.SeasonId
	}
	return 0
}

func (x *R_S_UPDATE_SEASON) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *R_S_UPDATE_SEASON) GetNextUpdateTime() uint64 {
	if x != nil {
		return x.NextUpdateTime
	}
	return 0
}

///游戏服通知其他服务器更新名字
type G_S_MODIFY_NICK_NAME struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string `protobuf:"bytes,1,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"` //玩家昵称
}

func (x *G_S_MODIFY_NICK_NAME) Reset() {
	*x = G_S_MODIFY_NICK_NAME{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_server_protocol_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G_S_MODIFY_NICK_NAME) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G_S_MODIFY_NICK_NAME) ProtoMessage() {}

func (x *G_S_MODIFY_NICK_NAME) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_server_protocol_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G_S_MODIFY_NICK_NAME.ProtoReflect.Descriptor instead.
func (*G_S_MODIFY_NICK_NAME) Descriptor() ([]byte, []int) {
	return file_proto_files_server_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *G_S_MODIFY_NICK_NAME) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

///更新worldboss推送
type UPDATE_WORLD_BOSS_PUSH struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldBossId    int32  `protobuf:"varint,1,opt,name=world_boss_id,json=worldBossId,proto3" json:"world_boss_id,omitempty"`          //worldboss
	NextUpdateTime uint64 `protobuf:"varint,2,opt,name=next_update_time,json=nextUpdateTime,proto3" json:"next_update_time,omitempty"` //下次更新时间
}

func (x *UPDATE_WORLD_BOSS_PUSH) Reset() {
	*x = UPDATE_WORLD_BOSS_PUSH{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_server_protocol_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UPDATE_WORLD_BOSS_PUSH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPDATE_WORLD_BOSS_PUSH) ProtoMessage() {}

func (x *UPDATE_WORLD_BOSS_PUSH) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_server_protocol_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPDATE_WORLD_BOSS_PUSH.ProtoReflect.Descriptor instead.
func (*UPDATE_WORLD_BOSS_PUSH) Descriptor() ([]byte, []int) {
	return file_proto_files_server_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *UPDATE_WORLD_BOSS_PUSH) GetWorldBossId() int32 {
	if x != nil {
		return x.WorldBossId
	}
	return 0
}

func (x *UPDATE_WORLD_BOSS_PUSH) GetNextUpdateTime() uint64 {
	if x != nil {
		return x.NextUpdateTime
	}
	return 0
}

var File_proto_files_server_protocol_proto protoreflect.FileDescriptor

var file_proto_files_server_protocol_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x16, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x09, 0x52, 0x5f, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54,
	0x12, 0x27, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x50,
	0x74, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x50, 0x74, 0x22, 0x89, 0x01, 0x0a, 0x0f, 0x47, 0x5f,
	0x52, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x70, 0x62,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x50, 0x74, 0x52,
	0x03, 0x70, 0x62, 0x70, 0x12, 0x2f, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x74, 0x52, 0x07, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x6f, 0x0a, 0x0d, 0x47, 0x5f, 0x52, 0x5f, 0x4a, 0x4f, 0x49,
	0x4e, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x03,
	0x70, 0x62, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x50,
	0x74, 0x52, 0x03, 0x70, 0x62, 0x70, 0x22, 0x58, 0x0a, 0x0f, 0x47, 0x5f, 0x52, 0x5f, 0x53, 0x45,
	0x41, 0x52, 0x43, 0x48, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x70, 0x62, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x50, 0x74, 0x52, 0x03, 0x70, 0x62, 0x70,
	0x22, 0x7a, 0x0a, 0x0b, 0x42, 0x5f, 0x53, 0x5f, 0x53, 0x55, 0x4d, 0x4d, 0x41, 0x52, 0x59, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x74, 0x65,
	0x72, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x50, 0x74, 0x52,
	0x0b, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x0b,
	0x42, 0x5f, 0x52, 0x5f, 0x53, 0x55, 0x4d, 0x4d, 0x41, 0x52, 0x59, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x22, 0xa0, 0x02, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x50, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x67, 0x72, 0x61, 0x64, 0x65, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x75, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x73, 0x6f, 0x75, 0x6c, 0x12, 0x28, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c,
	0x65, 0x61, 0x67, 0x75, 0x65, 0x50, 0x74, 0x52, 0x06, 0x6c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x12,
	0x38, 0x0a, 0x0c, 0x70, 0x75, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50,
	0x75, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x74, 0x52, 0x0b, 0x70, 0x75,
	0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x29, 0x0a, 0x05, 0x63, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x50, 0x74, 0x52, 0x05, 0x63,
	0x74, 0x65, 0x72, 0x73, 0x22, 0x4e, 0x0a, 0x12, 0x42, 0x5f, 0x52, 0x5f, 0x47, 0x5f, 0x50, 0x55,
	0x4e, 0x49, 0x53, 0x48, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x12, 0x38, 0x0a, 0x0c, 0x70, 0x75,
	0x6e, 0x69, 0x73, 0x68, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x75, 0x6e, 0x69, 0x73, 0x68,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x74, 0x52, 0x0b, 0x70, 0x75, 0x6e, 0x69, 0x73, 0x68, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x5f, 0x47, 0x5f, 0x53, 0x59, 0x4e, 0x43,
	0x5f, 0x52, 0x41, 0x4e, 0x4b, 0x22, 0x70, 0x0a, 0x11, 0x52, 0x5f, 0x53, 0x5f, 0x55, 0x50, 0x44,
	0x41, 0x54, 0x45, 0x5f, 0x53, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x28, 0x0a,
	0x10, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6e, 0x65, 0x78, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x14, 0x47, 0x5f, 0x53, 0x5f, 0x4d,
	0x4f, 0x44, 0x49, 0x46, 0x59, 0x5f, 0x4e, 0x49, 0x43, 0x4b, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x12,
	0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x66, 0x0a, 0x16,
	0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x57, 0x4f, 0x52, 0x4c, 0x44, 0x5f, 0x42, 0x4f, 0x53,
	0x53, 0x5f, 0x50, 0x55, 0x53, 0x48, 0x12, 0x22, 0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x5f,
	0x62, 0x6f, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x42, 0x6f, 0x73, 0x73, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x6e, 0x65,
	0x78, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6e, 0x65, 0x78, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_files_server_protocol_proto_rawDescOnce sync.Once
	file_proto_files_server_protocol_proto_rawDescData = file_proto_files_server_protocol_proto_rawDesc
)

func file_proto_files_server_protocol_proto_rawDescGZIP() []byte {
	file_proto_files_server_protocol_proto_rawDescOnce.Do(func() {
		file_proto_files_server_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_server_protocol_proto_rawDescData)
	})
	return file_proto_files_server_protocol_proto_rawDescData
}

var file_proto_files_server_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_files_server_protocol_proto_goTypes = []interface{}{
	(*R_B_START)(nil),              // 0: protos.R_B_START
	(*G_R_CREATE_ROOM)(nil),        // 1: protos.G_R_CREATE_ROOM
	(*G_R_JOIN_ROOM)(nil),          // 2: protos.G_R_JOIN_ROOM
	(*G_R_SEARCH_ROOM)(nil),        // 3: protos.G_R_SEARCH_ROOM
	(*B_S_SUMMARY)(nil),            // 4: protos.B_S_SUMMARY
	(*B_R_SUMMARY)(nil),            // 5: protos.B_R_SUMMARY
	(*PlayerBattlePt)(nil),         // 6: protos.PlayerBattlePt
	(*B_R_G_PUNISH_MATCH)(nil),     // 7: protos.B_R_G_PUNISH_MATCH
	(*R_G_SYNC_RANK)(nil),          // 8: protos.R_G_SYNC_RANK
	(*R_S_UPDATE_SEASON)(nil),      // 9: protos.R_S_UPDATE_SEASON
	(*G_S_MODIFY_NICK_NAME)(nil),   // 10: protos.G_S_MODIFY_NICK_NAME
	(*UPDATE_WORLD_BOSS_PUSH)(nil), // 11: protos.UPDATE_WORLD_BOSS_PUSH
	(*RoomPt)(nil),                 // 12: protos.RoomPt
	(*RoomSettingPt)(nil),          // 13: protos.RoomSettingPt
	(*SummaryDataPt)(nil),          // 14: protos.SummaryDataPt
	(*LeaguePt)(nil),               // 15: protos.LeaguePt
	(*PunishMatchPt)(nil),          // 16: protos.PunishMatchPt
	(*CharacterPt)(nil),            // 17: protos.CharacterPt
}
var file_proto_files_server_protocol_proto_depIdxs = []int32{
	12, // 0: protos.R_B_START.room_pt:type_name -> protos.RoomPt
	6,  // 1: protos.G_R_CREATE_ROOM.pbp:type_name -> protos.PlayerBattlePt
	13, // 2: protos.G_R_CREATE_ROOM.setting:type_name -> protos.RoomSettingPt
	6,  // 3: protos.G_R_JOIN_ROOM.pbp:type_name -> protos.PlayerBattlePt
	6,  // 4: protos.G_R_SEARCH_ROOM.pbp:type_name -> protos.PlayerBattlePt
	14, // 5: protos.B_S_SUMMARY.summary_data:type_name -> protos.SummaryDataPt
	15, // 6: protos.PlayerBattlePt.league:type_name -> protos.LeaguePt
	16, // 7: protos.PlayerBattlePt.punish_match:type_name -> protos.PunishMatchPt
	17, // 8: protos.PlayerBattlePt.cters:type_name -> protos.CharacterPt
	16, // 9: protos.B_R_G_PUNISH_MATCH.punish_match:type_name -> protos.PunishMatchPt
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_files_server_protocol_proto_init() }
func file_proto_files_server_protocol_proto_init() {
	if File_proto_files_server_protocol_proto != nil {
		return
	}
	file_proto_files_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_files_server_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*R_B_START); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_server_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G_R_CREATE_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_server_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G_R_JOIN_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_server_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G_R_SEARCH_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_server_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B_S_SUMMARY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_server_protocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B_R_SUMMARY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_server_protocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBattlePt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_server_protocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B_R_G_PUNISH_MATCH); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_server_protocol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*R_G_SYNC_RANK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_server_protocol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*R_S_UPDATE_SEASON); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_server_protocol_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G_S_MODIFY_NICK_NAME); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_server_protocol_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UPDATE_WORLD_BOSS_PUSH); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_server_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_files_server_protocol_proto_goTypes,
		DependencyIndexes: file_proto_files_server_protocol_proto_depIdxs,
		MessageInfos:      file_proto_files_server_protocol_proto_msgTypes,
	}.Build()
	File_proto_files_server_protocol_proto = out.File
	file_proto_files_server_protocol_proto_rawDesc = nil
	file_proto_files_server_protocol_proto_goTypes = nil
	file_proto_files_server_protocol_proto_depIdxs = nil
}
